# Generated by Django 6.0.8 on 2026-08-17 06:35

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('slug', models.SlugField(max_length=32, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=245)),
                ('sort_key', models.CharField(blank=True, max_length=255, null=True)),
                ('bandcamp_subdomain', models.CharField(blank=True, help_text='If the artist uses Bandcamp, otherwise leave blank', max_length=255, null=True, validators=[django.core.validators.RegexValidator(code='invalid_subdomain', message='Must be a valid subdomain.', regex='^[a-z0-9][a-z0-9-]+[a-z0-9]')])),
                ('musicbrainz', models.UUIDField(blank=True, null=True, verbose_name='MusicBrainz ID')),
                ('wikipedia_title', models.CharField(blank=True, help_text='Should use underscores instead of spaces and be a valid MediaWiki title', max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Release',
            fields=[
                ('slug', models.SlugField(max_length=32, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('single', models.BooleanField(default=False, help_text="Whether the track is a single. Doesn't make a difference except for labels.")),
                ('cover', models.ImageField(blank=True, help_text='Full-resolution covers should not be uploaded except in some rare cases (Lena Raine\'s "PhantomaOS", CC BY-SA, or Gayle\'s "abcdefu", public domain) due to copyright issues. Use ImageMagick to resize to 300x300.', null=True, upload_to='')),
                ('notes', models.TextField(blank=True, null=True)),
                ('bandcamp', models.BooleanField(verbose_name='On Bandcamp')),
                ('bandcamp_subdomain', models.CharField(blank=True, help_text='Must be used with Bandcamp slug.', null=True, validators=[django.core.validators.RegexValidator(code='invalid_subdomain', message='Must be a valid subdomain.', regex='^[a-z0-9][a-z0-9-]+[a-z0-9]')])),
                ('bandcamp_slug', models.SlugField(blank=True, help_text='Must be used with Bandcamp subdomain.', null=True)),
                ('bandcamp_id', models.PositiveBigIntegerField(blank=True, help_text='For embed player. On Bandcamp, click Embed, the wordpress.com, and find album=[...]. Fully optional.', null=True, verbose_name='Bandcamp album ID')),
                ('musicbrainz', models.UUIDField(blank=True, null=True, verbose_name='MusicBrainz ID')),
                ('artist', models.ForeignKey(blank=True, help_text='Leave blank for various artists', null=True, on_delete=django.db.models.deletion.CASCADE, to='music.artist')),
            ],
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=255)),
                ('release', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.release')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('release', 'number'), name='unique_release_track')],
            },
        ),
    ]
