# Generated by Django 6.1 on 2026-08-22 23:55

import music.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='release',
            name='cover',
            field=models.ImageField(blank=True, help_text='Full-resolution covers should not be uploaded except in some rare cases (Lena Raine\'s "PhantomaOS", CC BY-SA, or Gayle\'s "abcdefu", public domain) due to copyright. Use ImageMagick to resize to 300x300. Move to TheCrypt, paste into File Explorer: magick cover.png -resize 300x300 cover.png', null=True, upload_to=music.models.get_cover_filename),
        ),
    ]
