# Generated by Django 5.2.4 on 2025-07-31 06:30

import django.db.models.deletion
import martor.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('desc', martor.models.MartorField(verbose_name='Description')),
                ('banner', models.ImageField(upload_to='project-banners')),
                ('demo_url', models.URLField(verbose_name='Demo URL')),
                ('repo_url', models.URLField(verbose_name='Repository URL')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
