# Generated by Django 5.2.4 on 2025-07-31 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='allow_comments',
            field=models.BooleanField(default=True),
        ),
    ]
