# Generated by Django 6.0.3 on 2026-03-13 20:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doublefloat', '0005_alter_category_slug'),
        ('projects', '0003_project_allow_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='doublefloat_category',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='doublefloat.category'),
        ),
    ]
