# Generated by Django 6.0.3 on 2026-04-06 09:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doublefloat', '0005_alter_category_slug'),
        ('projects', '0004_project_doublefloat_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='doublefloat_category',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doublefloat_category', to='doublefloat.category'),
        ),
    ]
