# Generated by Django 6.1 on 2026-08-22 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_alter_project_doublefloat_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='allow_comments',
        ),
    ]
