# Generated by Django 6.1 on 2026-08-23 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_alter_project_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='project-banners'),
        ),
        migrations.AlterField(
            model_name='project',
            name='demo_url',
            field=models.URLField(blank=True, null=True, verbose_name='Demo URL'),
        ),
        migrations.AlterField(
            model_name='project',
            name='repo_url',
            field=models.URLField(blank=True, null=True, verbose_name='Repository URL'),
        ),
    ]
