# Generated by Django 6.1 on 2026-08-23 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_alter_project_banner_alter_project_demo_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='banner_alt',
            field=models.CharField(blank=True, max_length=511, null=True),
        ),
    ]
