# Generated by Django 6.1 on 2026-08-23 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_project_banner_alt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='banner_alt',
            field=models.CharField(blank=True, max_length=511, null=True, verbose_name='Banner alt text'),
        ),
    ]
