# Generated by Django 6.1 on 2026-08-24 04:42

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0005_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=255, unique=True, validators=[django.core.validators.DomainNameValidator()], verbose_name='Domain name')),
                ('name', models.CharField(max_length=255, verbose_name='Website name')),
            ],
        ),
        migrations.CreateModel(
            name='PersonalWebsite',
            fields=[
                ('link_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='cityfolk.link')),
                ('button', models.OneToOneField(blank=True, help_text="The website's 88x31 button.", null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.button')),
            ],
            bases=('cityfolk.link',),
        ),
    ]
