# Generated by Django 6.1 on 2026-08-24 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cityfolk', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='desc',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Description'),
        ),
    ]
