# Generated by Django 6.1 on 2026-08-23 05:28

import home.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Button',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.SlugField()),
                ('image', models.ImageField(help_text='Should be a PNG file, not a GIF or JPEG file. Especially not a WebP file.', upload_to=home.models.get_button_filename)),
                ('url', models.URLField(blank=True, null=True, verbose_name='URL')),
                ('alt', models.CharField(help_text='Required. Read by screen readers. Describe the image itself.', max_length=511, verbose_name='Alt text')),
                ('title', models.CharField(blank=True, help_text='Also known as the "hover text", also read by screen readers.', max_length=511, null=True)),
            ],
        ),
    ]
