# Generated by Django 6.1 on 2026-08-23 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='button',
            name='id',
            field=models.PositiveIntegerField(help_text='Sorted ascending.', primary_key=True, serialize=False, verbose_name='Sort key'),
        ),
    ]
