# Generated by Django 6.1 on 2026-08-24 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_button_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='button',
            name='featured',
            field=models.BooleanField(default=True, help_text='If False, only shown when linked to from another object.', verbose_name='Show on home page'),
            preserve_default=False,
        ),
    ]
