# Generated by Django 6.1 on 2026-08-24 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_button_featured'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Button',
        ),
    ]
