# Generated by Django 5.2.4 on 2025-07-31 03:45

import martor.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doublefloat', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'categories'},
        ),
        migrations.AlterField(
            model_name='category',
            name='desc',
            field=martor.models.MartorField(verbose_name='description'),
        ),
    ]
