# Generated by Django 5.2.4 on 2025-07-31 03:48

import martor.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doublefloat', '0002_alter_category_options_alter_category_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='desc',
            field=martor.models.MartorField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='post',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='category', to='doublefloat.category'),
        ),
    ]
