# Generated by Django 5.2.4 on 2025-07-31 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doublefloat', '0003_alter_category_desc_alter_post_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(blank=True, max_length=255),
        ),
    ]
