# Generated by Django 6.1 on 2026-08-22 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doublefloat', '0005_alter_category_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='allow_comments',
        ),
        migrations.AlterField(
            model_name='category',
            name='desc',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='post',
            name='body',
            field=models.TextField(),
        ),
    ]
