# Generated by Django 5.2.4 on 2025-08-02 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timemachine',
            name='hits',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
