# Generated by Django 6.0.3 on 2026-03-13 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pronums', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pronum',
            name='quote',
            field=models.BooleanField(default=False, help_text='Whether to show this pronum as a blockquote'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pronum',
            name='text',
            field=models.TextField(help_text="This will be placed inside an HTML list item. Don't use HTML. Use quote for blockquote format."),
        ),
    ]
