# Generated by Django 6.0.3 on 2026-03-13 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pronums', '0002_pronum_quote_alter_pronum_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pronum',
            name='quote',
            field=models.BooleanField(help_text='Whether to show this pronum as a blockquote', verbose_name='Show as quote'),
        ),
    ]
