# Generated by Django 6.0.3 on 2026-04-14 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pronums', '0003_alter_pronum_quote'),
    ]

    operations = [
        migrations.AddField(
            model_name='pronum',
            name='link_text',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='pronum',
            name='link_url',
            field=models.URLField(blank=True, max_length=300, null=True, verbose_name='Link URL'),
        ),
    ]
