name: Deploy Nest
on:
  push:
    branches:
      - main
jobs:
  deploy:
    if: github.repository == 'twonfi/twonum.org'
    runs-on: nest
    steps:
    - name: Setup
      run: |
        cd $HOME/twonum.org
        source .venv/bin/activate
    - name: Pull
      run: |
        git pull
    - name: Migrate
      run: |
        python3 collectstatic --noinput
        python3 manage.py migrate
    - name: Restart
      run: |
        systemctl --user restart twonum.org
