name: Deploy Nest
concurrency: nest
on:
  push:
    branches:
      - main
jobs:
  deploy:
    if: github.repository == 'twonfi/twonum.org'
    runs-on: [ self-hosted, nest ]
    environment: nest
    defaults:
      run:
        working-directory: /home/twonum/twonum.org
    steps:
    - name: Pull
      run: |
        git pull
    - name: Migrate
      run: |
        source .venv/bin/activate
        python3 manage.py collectstatic --noinput
        python3 manage.py migrate
    - name: Restart
      run: |
        systemctl --user restart twonum.org
