name: Deploy Nest
on:
  push:
    branches:
      - main
jobs:
  deploy:
    if: github.repository == 'twonfi/twonum.org'
    runs-on: [ self-hosted, nest ]
    steps:
    - name: Nest shell
      run: |
        cd $HOME/twonum.org
        source .venv/bin/activate
        git pull
        python3 manage.py collectstatic --noinput
        python3 manage.py migrate
        systemctl --user restart twonum.org
